//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XapkPackagingTool.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.11.0.0")]
    internal sealed partial class Path : global::System.Configuration.ApplicationSettingsBase {
        
        private static Path defaultInstance = ((Path)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Path())));
        
        public static Path Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Asset\\\\about\\\\external_components.json")]
        public string AssetUsedComponentsJsonDataPath {
            get {
                return ((string)(this["AssetUsedComponentsJsonDataPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Asset\\xapk\\install_locations.json")]
        public string AssetExpansionInstallLocations {
            get {
                return ((string)(this["AssetExpansionInstallLocations"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Asset\\xapk\\permissions.json")]
        public string AssetPredefinedPermissions {
            get {
                return ((string)(this["AssetPredefinedPermissions"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Asset\\xapk\\locale_codes.json")]
        public string AssetLocales {
            get {
                return ((string)(this["AssetLocales"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Asset\\xapk\\app_binary_interfaces.json")]
        public string AssetApplicationBinaryInterfaces {
            get {
                return ((string)(this["AssetApplicationBinaryInterfaces"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Asset\\xapk\\density_qualifiers.json")]
        public string AssetDensityQualifiers {
            get {
                return ((string)(this["AssetDensityQualifiers"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Asset\\\\xapk\\\\blank_project_template.json")]
        public string AssetBlankProjectTemplate {
            get {
                return ((string)(this["AssetBlankProjectTemplate"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("XapkPackagingTool")]
        public string AppDataDir {
            get {
                return ((string)(this["AppDataDir"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("recent_files.json")]
        public string RecentsFile {
            get {
                return ((string)(this["RecentsFile"]));
            }
        }
    }
}
